### ISSUE TITLE
retire draft-ERC20Permit.sol

### ISSUE THREAD

**Issue by SvenMeyer** [defi-wonderland/xERC20#3]
In `contracs/XERC20.sol`, think you can replace `ERC20/extensions/draft-ERC20Permit.sol`
with `ERC20/extensions/ERC20Permit.sol` especially as there is no `draft-ERC20Permit.sol` in @openzeppelin/contracts v5 any more.

**Comment by SvenMeyer** [comment]
like this ...
https://github.com/polkastarter/xERC20/commit/b9c2e520c65738343231fbfa46f0b6d48ef28894

**Comment by 0xShaito** [comment]
https://github.com/defi-wonderland/xERC20/commit/36a9d3b368a06c269129c4b46e946274b8128be2
