### ISSUE TITLE
do not enforce x+TOKENNAME

### ISSUE THREAD

**Issue by SvenMeyer** [defi-wonderland/xERC20#4]
I think it should be left to the token issuer how to name their token. (I already know one project which I can not convince to add an 'x' before the token name).

Thus the constructor would look like this : 

```solidity
constructor(
        string memory _name,
        string memory _symbol,
        address _factory
    ) ERC20(_name, _symbol) ERC20Permit(_name) Ownable(_factory) {
        // _transferOwnership(_factory); // not needed any more
        FACTORY = _factory;
    }
```

**Comment by SvenMeyer** [comment]
like this
https://github.com/polkastarter/xERC20/commit/f6930ceaa656442ef6fa307475508ba353bc7607

**Comment by 0xShaito** [comment]
Fixed here: https://github.com/defi-wonderland/xERC20/commit/36a9d3b368a06c269129c4b46e946274b8128be2
